
server:
  port: 8012

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: users-status-check
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/users/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ms/users/check,/users/check
            - AuthorizationHeaderFilter
        - id: users-ws-h2-console
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/h2-console
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ms/(?<segment>.*), /$\{segment}
        - id: users-create
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ms/(?<segment>.*), /$\{segment}
        - id: users-login
          uri: lb://users-ms
          predicates:
            - Path=/users-ms/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ms/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

token:
  secret: dgjorufhrsnjdu438fkdj38fdmcv7dm3ckvhrsnjjuwelueivhe848fhedldh5ndk
