spring:
  profiles:
    active: native,git
  application:
    name: PhotoAppConfigServer
  cloud:
    config:
      server:
        git:
          uri: git@github.com:kys20548/PhotoAppConfigServer.git
          ignore-local-ssh-settings: true
          search-paths: PhotoAppConfigServer
          default-label: main
          private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            -----END OPENSSH PRIVATE KEY-----
        native:
          search-locations: file://${user.home}/Desktop/dev/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8011

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
